[package]
name = "rustio"
version = "0.1.5"
edition = "2021"

[dependencies]
cpal = "0.15.2"
hound = "3.5.1"
rustfft = "6.1.0"
realfft = "3.3.0"
rand = "0.8"
audiopus = "0.3.0-rc.0"
ogg = "0.8.0"
opus = "0.3.0"